### ISSUE TITLE
Explorer throws error after being authenticated successfully

### ISSUE THREAD

**Issue by dark-eraser** [felixnext/whoopy#9]
I get the following when starting the streamlit app using `streamlit run explorer.py`. 
The authentication goes through successfully, but the client is unable to load the data for some reason. The error stays the same even when  I change the days slider or the data category. I tried to see what the problem could be but the issue that the error indicates : the date time object not being the right type / invalid is false as I tested it and it came back with the correct value and type.
I am a bit clueless right as to what could be the issue :-/

```bash
ValidationError: 1 validation error for UserCycle end Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType] For further information visit https://errors.pydantic.dev/2.6/v/datetime_type
Traceback:
File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "/Users/darkeraser/Documents/dev/whoopy/tools/explorer/explorer.py", line 185, in <module>
    rec, sleep, cycle, workout = load_metrics(baseline_days, today)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 709, in wrapped_func
    return get_or_create_cached_value()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/legacy_caching/caching.py", line 690, in get_or_create_cached_value
    return_value = non_optional_func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/darkeraser/Documents/dev/whoopy/tools/explorer/explorer.py", line 176, in load_metrics
    cycle, _ = client.cycle.collection_df(start=start, end=today, get_all_pages=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/whoopy/handlers/handler_v1.py", line 158, in collection_df
    recs, token = self.collection(
                  ^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/whoopy/handlers/handler_v1.py", line 136, in collection
    items = [self._model.from_dict(c, correct_offset=correct_offset) for c in recs]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/whoopy/handlers/handler_v1.py", line 136, in <listcomp>
    items = [self._model.from_dict(c, correct_offset=correct_offset) for c in recs]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/whoopy/models/models_v1.py", line 73, in from_dict
    return cls(**data)
           ^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
```

**Comment by felixnext** [comment]
Hey @dark-eraser, let me validate this tomorrow. Been a while since I written that code, so there might be some API changes.

**Comment by Aarekaz** [comment]
yeah, seems like there are some API changes.

I am also getting the same error. Any ideas? I could not figure it out

**Comment by dark-eraser** [comment]
Edit: actually I had to change the start and today values to manually set dates like so : "2024-05-01", because I could not find a way to format the available variables correctly to make it work
this has been solved for me by just returning to the project after a few days and I did not change a thing :)

**Comment by felixnext** [comment]
Hey @dark-eraser and @Aarekaz ,

Sorry for the delay, been quite busy last few weeks. Have pushed a new version that should fix the issues. Basically this should have come about due to pydantic version not being pinned and switch to pydantic 2.0 in the background (seemingly forcing stronger none-checks). Updated the models.

Let me know if you still run into issues.

New version (0.2.1) should also be available through pip now.

**Comment by felixnext** [comment]
See comments above. Please let me know if we should reopen

**Comment by felixnext** [comment]
See comments above. Please let me know if we should reopen

**Comment by Aarekaz** [comment]
I updated it, but I get this error. I am not able to find out the correct method. Isnt it with the get prefix?
<img width="807" alt="image" src="https://github.com/felixnext/whoopy/assets/36888347/75bf2899-294c-4e7b-8ba1-1e8bc2807870">

**Comment by Aarekaz** [comment]
Same if I go with the example at playground.ipynb
<img width="988" alt="image" src="https://github.com/felixnext/whoopy/assets/36888347/29ba9d94-87af-408a-9a86-dff7b7ed045a">

**Comment by felixnext** [comment]
@Aarekaz  It seems the source code from which you are refering is not the default streamlit app, but something you adjusted? To give a bit of background here: I have two Whoop Handlers. One acts **"as user"** and is therefore getting an Auth Token. (called `whoopy.client_uv7.WhoopClient`). This one got the `get_recovery` functions. Then there is an official client that as **"on behalf of the user"** (through the App interface from whoop). That one has the `recovery` function. It seems the second error you shared is still from the same streamlit app as before not from a jupyter notebook.
Could you double check the errors on your end and tell me how you create the client? (And if the source code of `2_Whoop_Fragment` is open-source please link to it).

Additionally a log dump of the streamlit app would be helpful.
